---
title: "PC Priors"
format: html
---

```{r load-packages,message=FALSE,warning=FALSE}
library(tidyverse)
library(bayesrules)
library(rstan)
```

```{r load-data}
data("basketball")
```

```{r cleaning}
clean_basketball <- basketball %>%
  group_by(player_name) %>%
  filter((team == "TOT"|n() ==1) & games_played >= 11)
```

```{r pc-prior}
set.seed(6)

basketball_data_pc <- list(N = nrow(clean_basketball),
                        x = clean_basketball$avg_points,
                        mu = rep(0,nrow(clean_basketball)),
                        R = diag(nrow(clean_basketball)),
                        U = 0.968,
                        alpha = 0.01)

basketball_pc_fit <- stan(file = "basketball_PC.stan",
                          data = basketball_data_pc,
                          chains = 4,
                          warmup = 1000,
                          iter = 2000)
```

```{r gamma-prior}
set.seed(6)

basketball_data_gamma <- list(N = nrow(clean_basketball),
                        x = clean_basketball$avg_points,
                        mu = rep(0,nrow(clean_basketball)),
                        R = diag(nrow(clean_basketball)),
                        a = 1,
                        b = 0.0076)

basketball_gamma_fit <- stan(file = "basketball_gamma.stan",
                             data = basketball_data_gamma,
                             chains = 4,
                             warmup = 1000,
                             iter = 2000)
```



```{r}
print(basketball_pc_fit)
print(basketball_gamma_fit)
```


```{r}
library(bayesplot)

pp_mat_complete_pc <- extract(basketball_pc_fit, pars = "x_pred")[[1]]

ppc_dens_overlay(log(basketball_data_pc$x) - mean(log(basketball_data_pc$x)), pp_mat_complete_pc[1:50,]) +
  theme_classic() +
  labs(title = "PC Prior")

ppc_intervals(log(basketball_data_pc$x) - mean(log(basketball_data_pc$x)), yrep = pp_mat_complete_pc[1:50, ], prob = 0.5, prob_outer = 0.95) +
  theme_classic() +
  labs(title = "PC Prior")

pp_mat_complete_gamma <- extract(basketball_gamma_fit, pars = "x_pred")[[1]]

ppc_dens_overlay(log(basketball_data_gamma$x) - mean(log(basketball_data_gamma$x)), pp_mat_complete_gamma[1:50,]) +
  theme_classic() +
  labs(title = "Gamma Prior")

ppc_intervals(log(basketball_data_gamma$x) - mean(log(basketball_data_gamma$x)), yrep = pp_mat_complete_gamma[1:50, ], prob = 0.5, prob_outer = 0.95) +
  theme_classic() + 
  labs(title = "Gamma Prior")
```

```{r}
small_sample <- clean_basketball %>%
  filter(team %in% c("MIN"))
```


```{r}
set.seed(6)

basketball_data_pc_small <- list(N = nrow(small_sample),
                        x = small_sample$avg_points,
                        mu = rep(0,nrow(small_sample)),
                        R = diag(nrow(small_sample)),
                        U = 0.968,
                        alpha = 0.01)

basketball_pc_fit_small <- stan(file = "basketball_PC.stan",
                          data = basketball_data_pc_small,
                          chains = 4,
                          warmup = 1000,
                          iter = 2000)
```

```{r}
set.seed(6)

basketball_data_gamma_small <- list(N = nrow(small_sample),
                        x = small_sample$avg_points,
                        mu = rep(0,nrow(small_sample)),
                        R = diag(nrow(small_sample)),
                        a = 1,
                        b = 0.0076)

basketball_gamma_fit_small <- stan(file = "basketball_gamma.stan",
                          data = basketball_data_gamma_small,
                          chains = 4,
                          warmup = 1000,
                          iter = 2000)
```

```{r}
print(basketball_pc_fit_small)
print(basketball_gamma_fit_small)
```

```{r}
pp_mat_complete_pc_small <- extract(basketball_pc_fit_small, pars = "x_pred")[[1]]

ppc_dens_overlay(log(basketball_data_pc_small$x) - mean(log(basketball_data_pc_small$x)), pp_mat_complete_pc_small[1:50,]) +
  theme_classic() +
  labs(title = "PC Prior")

ppc_intervals(log(basketball_data_pc_small$x) - mean(log(basketball_data_pc_small$x)), yrep = pp_mat_complete_pc_small[1:50, ], prob = 0.5, prob_outer = 0.95) +
  theme_classic() +
  labs(title = "PC Prior")

pp_mat_complete_gamma_small <- extract(basketball_gamma_fit_small, pars = "x_pred")[[1]]

ppc_dens_overlay(log(basketball_data_gamma_small$x) - mean(log(basketball_data_gamma_small$x)), pp_mat_complete_gamma_small[1:50,]) +
  theme_classic() +
  labs(title = "Gamma Prior")

ppc_intervals(log(basketball_data_gamma_small$x) - mean(log(basketball_data_gamma_small$x)), yrep = pp_mat_complete_gamma_small[1:50, ], prob = 0.5, prob_outer = 0.95) +
  theme_classic() + 
  labs(title = "Gamma Prior")
```





